#DUBBOX
dubbox:
  application:
    name: blog-sso-web
    organization: dubbox
    owner: mzayy
  registry:
    protocol: zookeeper
    address: 192.168.142.129:2181
  annotation:
    package: cn.mzayy.blog.web.sso.web

server:
  port: 85