#DUBBOX
dubbox:
  application:
    name: xbin-store-service-redis1
    organization: dubbox1
    owner: binux1
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  annotation:
    package: cn.binux.redis1
  protocol:
    name: dubbo
    port: 208811
    #host: 192.168.125.1
    timeout: 300001
    threadpool: fixed1
    threads: 5001
    accepts: 10001
    serialization: kryo
    optimizer: cn.binux.serial.SerializationOptimizerImpl
  monitor:
    enabled: false
    address: 192.168.125.1:6060
    username: admin
    password: admin

server:
  port: 8512
