#DUBBOX
dubbox:
  application:
    name: blog-sso-serivce
    organization: dubbox
    owner: mzayy
  registry:
    protocol: zookeeper
    address: 123.112.66.6:2181
  annotation:
    package: cn.mzayy.blog.sso.service
  protocol:
    name: dubbo
    port: 20825
    host: 192.168.99.1
    timeout: 30000
    threadpool: fixed
    threads: 500
    accepts: 1000




druid:
    url: jdbc:mysql://123.112.66.6:3306/mzayy?characterEncoding=utf-8
    driver-class: com.mysql.jdbc.Driver
    username: root
    password: qwaszx
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-While-Idle: true
    test-on-return: false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j,config
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=false
    monitor:
          enabled: false
          druid-stat-view: /druid/*
          druid-web-stat-filter: /*
          allow: 127.0.0.1
          deny: 192.168.1.73
          login-username: admin
          login-password: 123456
          exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
          reset-enable: false
mybatis:
    type-aliases-package: cn.mzayy.blog.Mapper
    mapper-locations: classpath:mapper/*.xml



server:
  port: 8087


