#DUBBOX
dubbox:
  application:
    name: blog-web
    organization: dubbox
    owner: mzayy
  registry:
    protocol: zookeeper
    address: 192.168.142.129:2181
  annotation:
    package: cn.mzayy.blog.Controller

server:
  port: 8089


spring:
    redis:
        database: 0
        host: 172.31.19.222
        password: ''
        pool:
            max-active: 8
            max-idle: 8
            max-wait: -1
            min-idle: 0
        port: 6379
